backend:
  name: local

media_folder: "images/uploads"
public_folder: "/images/uploads"

locale: "en"

display_url: https://eventdecorsigns.com

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["Welcome Signs", "Table Numbers", "Dance Floor Decals", "Signs & Displays", "Stickers"]}
      - {label: "Featured", name: "featured", widget: "boolean"}

  - name: "posts"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
